#ifndef __COMMON_CODEBASE_VERSION__
#define __COMMON_CODEBASE_VERSION__

/* This file is generated by script. */
#define CODE_VERSION     "ec80d7438"
#define CURRENT_BRANCH   "CUST/AND_SPA300_MJ1.3"
#define RLS_BOARD "SPA300-DEMO"
#define RLS_PROJECT "sunplus_main_SPA300"

#endif /* __COMMON_CODEBASE_VERSION__ */

