#ifndef __VFD_Nec16312_Drv_H
#define __VFD_Nec16312_Drv_H

#include "types.h"

#define DOT_DISC	(0x7f)
#define DOT_USB     (0x7f)
#define DOT_CARD    (0x7f)
#define DOT_IPOD    (0x7f)
#define DOT_BT		(0x7f)
#define DOT_FM		(0x7f)

#define DOT_STEREO	(0x7f)
#define DOT_MUTE	(0x7f)
#define DOT_REPEAT  (0x7f)

/* tingwei mark
#define DOT_COLON1  (0x7f)
#define DOT_COLON2	(0x18)//0x27
*/
#define DOT_COLON1  (24)
#define DOT_COLON2	(40)

#define DOT_DOT1	(0x28)//(0x7f)//xiaojian.wang change 2015-01-05
#define DOT_DOT2	(0x7f)
#define DOT_DOT3	(0x7f)
#define DOT_MHZ     (0x7f)

/*
** Definition for 7-seg display
**
** we assume 7-seg are defined as traditional 7-segment LED.
**
**	 AAAA
**	C    B
**	C    B
**	 DDDD
**	F    E
**	F    E
**	 GGGG
**
**

*/

#define	VFD_7SEG_SA	(0x01)
#define	VFD_7SEG_SB	(0x02)
#define	VFD_7SEG_SE	(0x04)
#define	VFD_7SEG_SG	(0x08)
#define	VFD_7SEG_SF	(0x10)
#define	VFD_7SEG_SC	(0x20)
#define	VFD_7SEG_SD (0x40)



#define	VFD_7SEG_0	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SG|VFD_7SEG_SC|VFD_7SEG_SE|VFD_7SEG_SF)
#define	VFD_7SEG_1	(VFD_7SEG_SB|VFD_7SEG_SE)
#define	VFD_7SEG_2	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_3	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_4	(VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SB|VFD_7SEG_SE)
#define	VFD_7SEG_5	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_6	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_7	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SE)
#define	VFD_7SEG_8	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_9	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_DIG_MASK	(VFD_7SEG_8)

#define	VFD_7SEG_A	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SD)
#define	VFD_7SEG_b	(VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_B	VFD_7SEG_b
#define	VFD_7SEG_C	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_d	(VFD_7SEG_SB|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_D	VFD_7SEG_d
#define	VFD_7SEG_E	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_F	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF)
#define	VFD_7SEG_G	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_H	(VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SE)
#define	VFD_7SEG_I	(VFD_7SEG_SB|VFD_7SEG_SE)
#define	VFD_7SEG_J	(VFD_7SEG_SB|VFD_7SEG_SE|VFD_7SEG_SG|VFD_7SEG_SF)
#define	VFD_7SEG_K	(VFD_7SEG_SB|VFD_7SEG_SE|VFD_7SEG_SG|VFD_7SEG_SF)
#define	VFD_7SEG_L	(VFD_7SEG_SC|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_M	(VFD_7SEG_SF|VFD_7SEG_SD|VFD_7SEG_SE)
#define	VFD_7SEG_n	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SE|VFD_7SEG_SF)
#define	VFD_7SEG_N	VFD_7SEG_n

#define	VFD_7SEG_O	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SG|VFD_7SEG_SC|VFD_7SEG_SE|VFD_7SEG_SF)
#define	VFD_7SEG_P	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF)
#define	VFD_7SEG_Q	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF)
#define	VFD_7SEG_r	(VFD_7SEG_SD|VFD_7SEG_SF)
#define	VFD_7SEG_R	VFD_7SEG_r
#define	VFD_7SEG_S	(VFD_7SEG_SA|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_t	(VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SG)
#define	VFD_7SEG_T	VFD_7SEG_t
#define	VFD_7SEG_U	(VFD_7SEG_SC|VFD_7SEG_SB|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_V	(VFD_7SEG_SC|VFD_7SEG_SB|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_W	(VFD_7SEG_SC|VFD_7SEG_SB|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_X	(VFD_7SEG_SC|VFD_7SEG_SB|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_Y	(VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SB|VFD_7SEG_SE|VFD_7SEG_SG)
#define	VFD_7SEG_Z	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SD|VFD_7SEG_SF|VFD_7SEG_SG)
#define VFD_7SEG_DOT    (39)
#define VFD_7SEG_MASK  0xff


#define	VFDC_SET_DISP			(0<<6)
#define	VFDC_SET_DATA			(1<<6)
#define	VFDC_SET_ADDR			(3<<6)
#define	VFDC_DISP_CTRL			(2<<6)

#define	VFDC_SET_DISP_4D16S		(0<<0)
#define	VFDC_SET_DISP_5D16S		(1<<0)
#define	VFDC_SET_DISP_6D16S		(2<<0)
#define	VFDC_SET_DISP_7D15S		(3<<0)
#define	VFDC_SET_DISP_8D14S		(4<<0)
#define	VFDC_SET_DISP_9D13S		(5<<0)
#define	VFDC_SET_DISP_10D12S	(6<<0)
#define	VFDC_SET_DISP_11D11S	(7<<0)
#define	VFDC_SET_DISP_9D18S	    (9<<0)


#define	VFDC_SET_DATA_DISP		(0<<0)
#define	VFDC_SET_DATA_LED		(1<<0)
#define	VFDC_SET_DATA_READKEY	(2<<0)
#define	VFDC_SET_DATA_READSW	(3<<0)

#define	VFDC_SET_DATA_AUTOINC	(0<<2)
#define	VFDC_SET_DATA_FIXED		(1<<2)

#define	VFDC_SET_DATA_TEST		(1<<3)
#define	VFDC_SET_DATA_NORMAL	(0<<3)

#define	VFDC_DISP_CTRL_ON		(1<<3)
#define	VFDC_DISP_CTRL_OFF		(0<<3)

#define	VFDC_DISP_CTRL_1_16		(0<<0)
#define	VFDC_DISP_CTRL_2_16		(1<<0)
#define	VFDC_DISP_CTRL_4_16		(2<<0)
#define	VFDC_DISP_CTRL_10_16	(3<<0)
#define	VFDC_DISP_CTRL_11_16	(4<<0)
#define	VFDC_DISP_CTRL_12_16	(5<<0)
#define	VFDC_DISP_CTRL_13_16	(6<<0)
#define	VFDC_DISP_CTRL_14_16	(7<<0)



#define VFD_DISPLAY_MODE (VFDC_SET_DISP_4D16S)//(VFDC_SET_DISP_7D15S)//belong to hardware
#define TOTAL_SEG			(4)
#define TOTAL_DOT			(15)


typedef  struct
{
	UINT8 seg_p[TOTAL_SEG];
	UINT8 dot_num[TOTAL_DOT];

} VFD_DISP;
#endif


//extern void InitVfd(void);

