#ifndef __VFD_Pt6315_Drv_H
#define __VFD_Pt6315_Drv_H

#include "types.h"
#include "user_def.h"

/*
** Definition for 7-seg PT6315 display
**
**
**	aaaaaaaaaaaaaaaaaaa
**	f h   	j		k b
**	f	h	j	  k	  b
**	f 	 h	j	k	  b
**	f	  h	j k	      b  col
**	 gggggg s mmmmmmm
**	e	  r	p n		  c  col
**	e	 r	p	n	  c
**	e	r	p	  n	  c
**  e r     p      n  c
**  ddddddddddddddddddd  Dp
**
*/

#define	VFD_7SEG_SA	(0x1<<0)
#define	VFD_7SEG_SF	(0x1<<1)
#define	VFD_7SEG_SH	(0x1<<2)
#define	VFD_7SEG_SJ	(0x1<<3)
#define	VFD_7SEG_SK	(0x1<<4)
#define	VFD_7SEG_SB	(0x1<<5)
#define	VFD_7SEG_SG (0x1<<6)
#define	VFD_7SEG_SS (0x1<<7)
#define	VFD_7SEG_SM (0x1<<8)
#define	VFD_7SEG_SE (0x1<<9)
#define	VFD_7SEG_SR (0x1<<10)
#define	VFD_7SEG_SP (0x1<<11)
#define	VFD_7SEG_SN (0x1<<12)
#define	VFD_7SEG_SC (0x1<<13)
#define	VFD_7SEG_SD (0x1<<14)

#define	VFD_7SEG_0	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF)

#define	VFD_7SEG_1	(VFD_7SEG_SJ|VFD_7SEG_SS|VFD_7SEG_SP)

#define	VFD_7SEG_2	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SM|VFD_7SEG_SS|VFD_7SEG_SG|VFD_7SEG_SE|VFD_7SEG_SD)

#define	VFD_7SEG_3	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SM|VFD_7SEG_SS|VFD_7SEG_SG|VFD_7SEG_SC|VFD_7SEG_SD)

#define	VFD_7SEG_4	(VFD_7SEG_SF|VFD_7SEG_SG|VFD_7SEG_SS|VFD_7SEG_SM|VFD_7SEG_SB|VFD_7SEG_SC)

#define	VFD_7SEG_5	(VFD_7SEG_SA|VFD_7SEG_SF|VFD_7SEG_SG|VFD_7SEG_SS|VFD_7SEG_SM|VFD_7SEG_SC|VFD_7SEG_SD)

#define	VFD_7SEG_6	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SD|VFD_7SEG_SC|VFD_7SEG_SM|VFD_7SEG_SS|VFD_7SEG_SG|VFD_7SEG_SA)

#define	VFD_7SEG_7	(VFD_7SEG_SF|VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC)

#define	VFD_7SEG_8	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SG|VFD_7SEG_SS|VFD_7SEG_SM)

#define	VFD_7SEG_9	(VFD_7SEG_SF|VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SG|VFD_7SEG_SS|VFD_7SEG_SM|VFD_7SEG_SD)


#define	VFD_7SEG_A	(VFD_7SEG_SK|VFD_7SEG_SS|VFD_7SEG_SR|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SM)

#define	VFD_7SEG_B	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SJ|VFD_7SEG_SS|VFD_7SEG_SP|VFD_7SEG_SM)

#define	VFD_7SEG_C	(VFD_7SEG_SA|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SD)

#define	VFD_7SEG_D	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SJ|VFD_7SEG_SS|VFD_7SEG_SP)

#define	VFD_7SEG_E	(VFD_7SEG_SA|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SD|VFD_7SEG_SG|VFD_7SEG_SS|VFD_7SEG_SM)

#define	VFD_7SEG_F	(VFD_7SEG_SA|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SG|VFD_7SEG_SS)

#define	VFD_7SEG_G	(VFD_7SEG_SA|VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SD|VFD_7SEG_SC|VFD_7SEG_SM|VFD_7SEG_SS)

#define	VFD_7SEG_H	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SG|VFD_7SEG_SS|VFD_7SEG_SM)

#define	VFD_7SEG_I	(VFD_7SEG_SA|VFD_7SEG_SJ|VFD_7SEG_SS|VFD_7SEG_SP|VFD_7SEG_SD)

#define	VFD_7SEG_J	(VFD_7SEG_SA|VFD_7SEG_SJ|VFD_7SEG_SS|VFD_7SEG_SR)

#define	VFD_7SEG_K	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SK|VFD_7SEG_SS|VFD_7SEG_SG|VFD_7SEG_SN)

#define	VFD_7SEG_L	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SD)

#define	VFD_7SEG_M	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SH|VFD_7SEG_SS|VFD_7SEG_SP|VFD_7SEG_SK|VFD_7SEG_SB|VFD_7SEG_SC)

#define	VFD_7SEG_N	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SH|VFD_7SEG_SS|VFD_7SEG_SN|VFD_7SEG_SB|VFD_7SEG_SC)

#define	VFD_7SEG_O	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF)

#define	VFD_7SEG_P	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SM|VFD_7SEG_SS|VFD_7SEG_SG)

#define	VFD_7SEG_Q	(VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF|VFD_7SEG_SN)

#define	VFD_7SEG_R	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SA|VFD_7SEG_SB|VFD_7SEG_SM|VFD_7SEG_SS|VFD_7SEG_SG|VFD_7SEG_SN)

#define	VFD_7SEG_S	(VFD_7SEG_SA|VFD_7SEG_SF|VFD_7SEG_SG|VFD_7SEG_SS|VFD_7SEG_SM|VFD_7SEG_SC|VFD_7SEG_SD)

#define	VFD_7SEG_T	(VFD_7SEG_SA|VFD_7SEG_SJ|VFD_7SEG_SS|VFD_7SEG_SP)

#define	VFD_7SEG_U	(VFD_7SEG_SB|VFD_7SEG_SC|VFD_7SEG_SD|VFD_7SEG_SE|VFD_7SEG_SF)

#define	VFD_7SEG_V	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SR|VFD_7SEG_SS|VFD_7SEG_SK)

#define	VFD_7SEG_W	(VFD_7SEG_SF|VFD_7SEG_SE|VFD_7SEG_SR|VFD_7SEG_SS|VFD_7SEG_SJ|VFD_7SEG_SN|VFD_7SEG_SC|VFD_7SEG_SB)

#define	VFD_7SEG_X	(VFD_7SEG_SH|VFD_7SEG_SS|VFD_7SEG_SN|VFD_7SEG_SK|VFD_7SEG_SR)

#define	VFD_7SEG_Y	(VFD_7SEG_SH|VFD_7SEG_SK|VFD_7SEG_SS|VFD_7SEG_SP)

#define	VFD_7SEG_Z	(VFD_7SEG_SA|VFD_7SEG_SK|VFD_7SEG_SS|VFD_7SEG_SR|VFD_7SEG_SD)


#define TOTAL_SEG			(8)
#endif



