/******************************************************************************/
/**
*
* \file	 custom_sig.h
*
* \brief	 signals for customer.\n
*
* \note  	Copyright (c) 2008 Sunplus Technology Co., Ltd. \n
*			All rights reserved.
*
*
* \author       Daniel.yeh@sunplus.com
*\version	 v0.01
*\date 	 2016/11/07
******************************************************************************/
#ifndef __CUSTOM_SIG_H__
#define __CUSTOM_SIG_H__

#include "qp_pub.h"


enum CUSTOM_QEVTSIG
{

	/*.................................customer public signals.........................................*/
	CUSTOMER_PUB_START_SIG = CUSTOMER_PUB_SIG_START,
	// add new customer publish signal below!!{ // DO NOT add customer publish signal more than 10!!
#if 0 // exemple
	/*.................................exemple ao publish signal.........................................*/
	EXEMPLE_PUB_A_SIG,
	EXEMPLE_PUB_B_SIG,
	EXEMPLE_PUB_C_SIG,
	EXEMPLE_PUB_D_SIG,
	//........

	/*..........................................................................*/
#endif
	// add new publish signal above!!}

	CUSTOMER_PUB_SIG_MAX,
	/*.................................customer private signals.........................................*/
	POWER_SIG = CUSTOMER_PRIVATE_SIG_START,
	POWER_RELEASE_SIG,
	POWER_LONG_PRESS_SIG,
	POWER_LONG_RELEASE_SIG,
	POWER_TICK_SIG,


	PLAY_SIG,                             //eKeyPress
	PLAY_RELEASE_SIG,             //eKeyRelease
	PLAY_LONG_PRESS_SIG,      //eKeyLongPress
	PLAY_LONG_RELEASE_SIG,  //eKeyLongRelease
	PLAY_TICK_SIG,                   //eKeyLongTick


	STOP_SIG,
	STOP_RELEASE_SIG,
	STOP_LONG_PRESS_SIG,
	STOP_LONG_RELEASE_SIG,
	STOP_TICK_SIG,

	PAUSE_SIG,
	PAUSE_RELEASE_SIG,
	PAUSE_LONG_PRESS_SIG,
	PAUSE_LONG_RELEASE_SIG,
	PAUSE_TICK_SIG,

	SOURCE_SW_SIG,
	SOURCE_SW_RELEASE_SIG,
	SOURCE_SW_LONG_PRESS_SIG,
	SOURCE_SW_LONG_RELEASE_SIG,
	SOURCE_SW_TICK_SIG,

	VOL_UP_SIG,
	VOL_UP_RELEASE_SIG,
	VOL_UP_LONG_PRESS_SIG,
	VOL_UP_LONG_RELEASE_SIG,
	VOL_UP_TICK_SIG,

	VOL_DOWN_SIG,
	VOL_DOWN_RELEASE_SIG,
	VOL_DOWN_LONG_PRESS_SIG,
	VOL_DOWN_LONG_RELEASE_SIG,
	VOL_DOWN_TICK_SIG,

	MUTE_SIG,//204
	MUTE_RELEASE_SIG,//205
	MUTE_LONG_PRESS_SIG,
	MUTE_LONG_RELEASE_SIG,
	MUTE_TICK_SIG,

	FF_SIG,
	FF_RELEASE_SIG,
	FF_LONG_PRESS_SIG,
	FF_LONG_RELEASE_SIG,
	FF_TICK_SIG,

	FB_SIG,
	FB_RELEASE_SIG,
	FB_LONG_PRESS_SIG,
	FB_LONG_RELEASE_SIG,
	FB_TICK_SIG,

	NEXT_SIG,
	NEXT_RELEASE_SIG,
	NEXT_LONG_PRESS_SIG,
	NEXT_LONG_RELEASE_SIG,
	NEXT_TICK_SIG,

	PRE_SIG,
	PRE_RELEASE_SIG,
	PRE_LONG_PRESS_SIG,
	PRE_LONG_RELEASE_SIG,
	PRE_TICK_SIG,

	REPEAT_SIG,
	REPEAT_RELEASE_SIG,
	REPEAT_LONG_PRESS_SIG,
	REPEAT_LONG_RELEASE_SIG,
	REPEAT_TICK_SIG,

	SHUFFLE_SIG,
	SHUFFLE_RELEASE_SIG,
	SHUFFLE_LONG_PRESS_SIG,
	SHUFFLE_LONG_RELEASE_SIG,
	SHUFFLE_TICK_SIG,

	SELECT_SIG,
	SELECT_RELEASE_SIG,
	SELECT_LONG_PRESS_SIG,
	SELECT_LONG_RELEASE_SIG,
	SELECT_TICK_SIG,

	SURROUND_3D_SIG,
	SURROUND_3D_RELEASE_SIG,
	SURROUND_3D_LONG_PRESS_SIG,
	SURROUND_3D_LONG_RELEASE_SIG,
	SURROUND_3D_TICK_SIG,

	EQ_SIG,
	EQ_RELEASE_SIG,
	EQ_LONG_PRESS_SIG,
	EQ_LONG_RELEASE_SIG,
	EQ_TICK_SIG,

	UP_SIG,
	UP_RELEASE_SIG,
	UP_LONG_PRESS_SIG,
	UP_LONG_RELEASE_SIG,
	UP_TICK_SIG,

	DOWN_SIG,
	DOWN_RELEASE_SIG,
	DOWN_LONG_PRESS_SIG,
	DOWN_LONG_RELEASE_SIG,
	DOWN_TICK_SIG,

	PROGRAM_SIG,
	PROGRAM_RELEASE_SIG,
	PROGRAM_LONG_PRESS_SIG,
	PROGRAM_LONG_RELEASE_SIG,
	PROGRAM_TICK_SIG,

	ZERO_SIG,
	ZERO_RELEASE_SIG,
	ZERO_LONG_PRESS_SIG,
	ZERO_LONG_RELEASE_SIG,
	ZERO_TICK_SIG,

	ONE_SIG,
	ONE_RELEASE_SIG,
	ONE_LONG_PRESS_SIG,
	ONE_LONG_RELEASE_SIG,
	ONE_TICK_SIG,

	TWO_SIG,
	TWO_RELEASE_SIG,
	TWO_LONG_PRESS_SIG,
	TWO_LONG_RELEASE_SIG,
	TWO_TICK_SIG,

	THREE_SIG,
	THREE_RELEASE_SIG,
	THREE_LONG_PRESS_SIG,
	THREE_LONG_RELEASE_SIG,
	THREE_TICK_SIG,

	FOUR_SIG,
	FOUR_RELEASE_SIG,
	FOUR_LONG_PRESS_SIG,
	FOUR_LONG_RELEASE_SIG,
	FOUR_TICK_SIG,

	FIVE_SIG,
	FIVE_RELEASE_SIG,
	FIVE_LONG_PRESS_SIG,
	FIVE_LONG_RELEASE_SIG,
	FIVE_TICK_SIG,

	SIX_SIG,
	SIX_RELEASE_SIG,
	SIX_LONG_PRESS_SIG,
	SIX_LONG_RELEASE_SIG,
	SIX_TICK_SIG,

	SEVEN_SIG,              //KOK_ECHO_UP_SIG,
	SEVEN_RELEASE_SIG,      //KOK_ECHO_UP_RELEASE_SIG,
	SEVEN_LONG_PRESS_SIG,   //KOK_ECHO_UP_LONG_PRESS_SIG,
	SEVEN_LONG_RELEASE_SIG, //KOK_ECHO_UP_LONG_RELEASE_SIG,
	SEVEN_TICK_SIG,         //KOK_ECHO_UP_TICK_SIG,

	EIGHT_SIG,
	EIGHT_RELEASE_SIG,
	EIGHT_LONG_PRESS_SIG,
	EIGHT_LONG_RELEASE_SIG,
	EIGHT_TICK_SIG,

	NINE_SIG,               //KOK_KEY_SHIFT_UP_SIG,
	NINE_RELEASE_SIG,       //KOK_KEY_SHIFT_UP_RELEASE_SIG,
	NINE_LONG_PRESS_SIG,    //KOK_KEY_SHIFT_UP_LONG_PRESS_SIG,
	NINE_LONG_RELEASE_SIG,  //KOK_KEY_SHIFT_UP_LONG_RELEASE_SIG,
	NINE_TICK_SIG,          //KOK_KEY_SHIFT_UP_TICK_SIG,

	KOK_ECHO_DN_SIG,
	KOK_ECHO_DN_RELEASE_SIG,
	KOK_ECHO_DN_LONG_PRESS_SIG,
	KOK_ECHO_DN_LONG_RELEASE_SIG,
	KOK_ECHO_DN_TICK_SIG,

	WSS_BT_PAIR_SIG,
	WSS_BT_PAIR_RELEASE_SIG,
	WSS_BT_PAIR_LONG_PRESS_SIG,
	WSS_BT_PAIR_LONG_RELEASE_SIG,
	WSS_BT_PAIR_TICK_SIG,


	BT_START_SEARCH_SIG,
	BT_START_SEARCH_RELEASE_SIG,
	BT_START_SEARCH_LONG_PRESS_SIG,
	BT_START_SEARCH_LONG_RELEASE_SIG,
	BT_START_SEARCH_TICK_SIG,

	BT_TWS_MODE_SWITCH_SIG,
	BT_TWS_MODE_SWITCH_RELEASE_SIG,
	BT_TWS_MODE_SWITCH_LONG_PRESS_SIG,
	BT_TWS_MODE_SWITCH_LONG_RELEASE_SIG,
	BT_TWS_MODE_SWITCH_TICK_SIG,

	BT_SOURCE_DISCONNECT_SIG,
	BT_SOURCE_DISCONNECT_RELEASE_SIG,
	BT_SOURCE_DISCONNECT_LONG_PRESS_SIG,
	BT_SOURCE_DISCONNECT_LONG_RELEASE_SIG,
	BT_SOURCE_DISCONNECT_TICK_SIG,

	WOOFER_VOL_UP_SIG,
	WOOFER_VOL_UP_RELEASE_SIG,
	WOOFER_VOL_UP_LONG_PRESS_SIG,
	WOOFER_VOL_UP_LONG_RELEASE_SIG,
	WOOFER_VOL_UP_TICK_SIG,

	WOOFER_VOL_DOWN_SIG,
	WOOFER_VOL_DOWN_RELEASE_SIG,
	WOOFER_VOL_DOWN_LONG_PRESS_SIG,
	WOOFER_VOL_DOWN_LONG_RELEASE_SIG,
	WOOFER_VOL_DOWN_TICK_SIG,

	CEC_MUTE_ON_SIG,
   	CEC_MUTE_OFF_SIG,
    CEC_POWER_OFF_SIG,
    CEC_POWER_ON_SIG,

	//KOK_EN_SIG,
	//KOK_EN_RELEASE_SIG,
	//KOK_EN_LONG_PRESS_SIG,
	//KOK_EN_LONG_RELEASE_SIG,

	KOK_BGM_VOL_UP_SIG,
	KOK_BGM_VOL_UP_RELEASE_SIG,
	KOK_BGM_VOL_UP_LONG_PRESS_SIG,
	KOK_BGM_VOL_UP_LONG_RELEASE_SIG,
	KOK_BGM_VOL_UP_TICK_SIG,

	KOK_BGM_VOL_DN_SIG,
	KOK_BGM_VOL_DN_RELEASE_SIG,
	KOK_BGM_VOL_DN_LONG_PRESS_SIG,
	KOK_BGM_VOL_DN_LONG_RELEASE_SIG,
	KOK_BGM_VOL_DN_TICK_SIG,

	KOK_MIC1_VOL_UP_SIG,
	KOK_MIC1_VOL_UP_RELEASE_SIG,
	KOK_MIC1_VOL_UP_LONG_PRESS_SIG,
	KOK_MIC1_VOL_UP_LONG_RELEASE_SIG,
	KOK_MIC1_VOL_UP_TICK_SIG,

	KOK_MIC1_VOL_DN_SIG,
	KOK_MIC1_VOL_DN_RELEASE_SIG,
	KOK_MIC1_VOL_DN_LONG_PRESS_SIG,
	KOK_MIC1_VOL_DN_LONG_RELEASE_SIG,
	KOK_MIC1_VOL_DN_TICK_SIG,

	KOK_MIC2_VOL_UP_SIG,
	KOK_MIC2_VOL_UP_RELEASE_SIG,
	KOK_MIC2_VOL_UP_LONG_PRESS_SIG,
	KOK_MIC2_VOL_UP_LONG_RELEASE_SIG,
	KOK_MIC2_VOL_UP_TICK_SIG,

	KOK_MIC2_VOL_DN_SIG,
	KOK_MIC2_VOL_DN_RELEASE_SIG,
	KOK_MIC2_VOL_DN_LONG_PRESS_SIG,
	KOK_MIC2_VOL_DN_LONG_RELEASE_SIG,
	KOK_MIC2_VOL_DN_TICK_SIG,

	KOK_KEY_SHIFT_DN_SIG,
	KOK_KEY_SHIFT_DN_RELEASE_SIG,
	KOK_KEY_SHIFT_DN_LONG_PRESS_SIG,
	KOK_KEY_SHIFT_DN_LONG_RELEASE_SIG,
	KOK_KEY_SHIFT_DN_TICK_SIG,

	KOK_VC_LVL_SIG,
	KOK_VC_LVL_RELEASE_SIG,
	KOK_VC_LVL_LONG_PRESS_SIG,
	KOK_VC_LVL_LONG_RELEASE_SIG,
	KOK_VC_LVL_TICK_SIG,

	KOK_NR_SIG,
	KOK_NR_RELEASE_SIG,
	KOK_NR_LONG_PRESS_SIG,
	KOK_NR_LONG_RELEASE_SIG,
	KOK_NR_TICK_SIG,

	BT_SIG,
	BT_RELEASE_SIG,
	BT_LONG_PRESS_SIG,
	BT_LONG_RELEASE_SIG,
	BT_TICK_SIG,

	USB_SIG,
	USB_RELEASE_SIG,
	USB_LONG_PRESS_SIG,
	USB_LONG_RELEASE_SIG,
	USB_TICK_SIG,

	CUSTOMER_KEY_SIG_MAX = KOK_NR_TICK_SIG,

	KOK_TURN_ON_SIG,
	KOK_TURN_OFF_SIG,

	BT_AUTO_PLAY_SIG,
	BT_MUSIC_PLAY_REQ_SIG,
	BT_MUSIC_PUASE_REQ_SIG,
	BT_MUSIC_NEXT_REQ_SIG,
	BT_MUSIC_PREV_REQ_SIG,
	BT_VOL_SYNC_SET_SIG,
	BT_VOL_SET_SUB_GAIN_SIG,
	BT_READY_SOUNDHINT_SIG,
	BT_CONNECT_SOUNDHINT_SIG,

	UPGRADE_SHOW_PERCENTAGE_SIG,
	POWER_OFF_SIG,

	SET_BT_SOURCE_SIG,

	CUSTOM_TEST_AUTOSWITCHSRC_SIG,
	CUSTOM_TEST_POWEROFF_SIG,
	CUSTOM_TEST_AUTO_REPEAT_SIGNAL_SIG,
	CUSTOM_CHECK_TAS5352A_SD_OTW_SIG,
	/*..................................user app led private signal.....................................*/
	LED_CONST_SIG,
	LED_BLINK_SIG,

	CUSTOM_HINT_START_SIG,
	CUSTOM_HINT_END_SIG,

	CEC_EVT_SIG,
	AUDIO_INFO_BROADCAST_SIG,
	AUDIO_MUTE_SET_SIG,
	AUDIO_VOL_SET_SIG,
	MF_ERR_UNSUPPORT_SIG,
	IR_LEARNING_DONE_SIG,

	SRV_AO_READY_SIG,

	DISPLAY_TICK_SIG,
	DISPLAY_GET_KEY_SIG,
	DISPLAY_VFD_CONST_SIG,
	DISPLAY_VFD_SCOLL_SIG,
	DISPLAY_VFD_BLINK_SIG,
	DISPLAY_VFD_DISPLAY_SIG,
	DISPLAY_VFD_ALIGN_SIG,
	DISPLAY_VFD_POP_SIG,
	DISPLAY_VFD_COUNTER_SIG,
	DISPLAY_VFD_Play_Time_SIG,
	DISPLAY_VFD_SHOWDARK_SIG,
	DISPLAY_VFD_DOT_SIG,
	DISPLAY_VFD_BLINKONE_CONST_SIG,
	DISPLAY_VFD_SCOLLONE_CONST_SIG,

	DISPLAY_LED_DISPLAY_SIG,
	DISPLAY_LED_CONST_SIG,
	DISPLAY_LED_BLINK_SIG,
	DISPLAY_LED_COUNTER_SIG,
	DISPLAY_LED_SHOWDARK_SIG,

	MCU_IF_USER_VOLSET_SIG,
	MCU_IF_USER_SWITCHSRC_SIG,
	MCU_IF_USER_UPGRADE_START_SIG,
	MCUIF_UPGRADE_TERMINATE_SIG,
	MCU_IF_USER_BAUDSET0_SIG,
	MCU_IF_USER_BAUDSET1_SIG,
	MCU_IF_USER_BAUDSET2_SIG,
	MCU_IF_USER_BAUDSET3_SIG,

	WATCHDOG_TICK_SIG,
	REPEATER_EX_INTR_0_SIG,
	REPEATER_SRC_SWITCH_SIG,
	REPEATER_USER_SWITCHSRC_SIG,
	REPEATER_POWER_UP_SIG,
	REPEATER_POWER_DOWN_SIG,
	EPEATER_USER_POWER_UP_SIG,
	REPEATER_VOL_SET_SIG,
	REPEATER_MUTE_SET_SIG,
	REPEATER_REG_PRINTF_SIG,
	REPEATER_AUD_SRC_SIG,
	REPEATER_AUD_ARC_SRC_SIG,
	REPEATER_HDMI_HPD_SIG,
	REPEATER_AUD_INFO_PRINTF_SIG,
	REPEATER_AUD_INFO_SEND_REQ_SIG,
	REPEATER_eARCSRC_CHANGE_SIG,
	REPEATER_DSPSourceID_SIG,
	REPEATER_eARCSource_SIG,
	REPEATER_MUTE_AUDIO_OUTPUT_SIG,
	REPEATER_AUDIO_PATH_SET_SIG,
	REPEATER_I2C_Ready_Polling_SIG,
	REPEATER_MUTE_SYN_SIG,
	REPEATER_EP_UPGRADE_SIG,
	REPEATER_LPCMCHANNEL_NUM_SIG,

	SERVICE_DESTROY_DONE_SIG,
	CHECK_AVDTP_STATE_SIG,

	/*****************userapp cli signal********************/
	USERAPP_CLI_SRC_USB_SIG,
	USERAPP_CLI_SRC_CARD_SIG,
	USERAPP_CLI_SRC_AUX_SIG,
	USERAPP_CLI_SRC_LINE_SIG,
	USERAPP_CLI_SRC_OPTICAL_SIG,
	USERAPP_CLI_SRC_COAXIAL_SIG,
	USERAPP_CLI_SRC_ARC_SIG,
	USERAPP_CLI_SRC_HDMI0_SIG,
	USERAPP_CLI_SRC_HDMI1_SIG,
	USERAPP_CLI_SRC_HDMI2_SIG,
	USERAPP_CLI_SRC_BT_SIG,
	USERAPP_CLI_BT_CLEAR_ALLBONDDEV_SIG,
	USERAPP_CLI_BT_ENTER_DUT_SIG,
    USERAPP_CLI_BT_REMOTE_INFO_SIG,
	USERAPP_CLI_BT_MUSIC_INFO_SIG,
	USERAPP_CLI_BT_PLAY_STATUS_SIG,
	USERAPP_CLI_BT_FORWARD_SEEK_SIG,
	USERAPP_CLI_BT_REVERSE_SEEK_SIG,
	USERAPP_CLI_BT_REMOTE_RSSI_SIG,
	USERAPP_CLI_BT_A2DP_CODEC_SIG,
	USERAPP_CLI_SRC_I2S_SIG,
	USERAPP_CLI_SRC_EARC_SIG,
	USERAPP_CLI_SRC_RAW_DATA_SIG,
	USERAPP_CLI_DEV_LIST_SIG,
	USERAPP_CLI_PLAY_DEV_NUM1_SIG,
	USERAPP_CLI_PLAY_DEV_NUM2_SIG,
	USERAPP_CLI_PLAY_DEV_NUM3_SIG,
	USERAPP_CLI_PLAY_DEV_NUM4_SIG,

	USERAPP_CLI_VA_TEST_SIG,
	USERAPP_CLI_AUXVA_SIG,
	USERAPP_CLI_BTVA_SIG,
	USERAPP_CLI_VAON_SIG,
	USERAPP_CLI_VAOFF_SIG,

	TIME_DEV_PLAY_SIG,
    SRC_HINT_TIME_SIG,
	HINT_DELAY_TIME_SIG,
	HINT_INTERVAL_TIME_SIG,

	RSR_TIMER_200ms_SIG,
	RSR_AudFmt_CHANGED_SIG,

	/*****************va signal********************/
	AUXVA_SW_SIG,
	BTVA_SW_SIG,
	ALL_VAON_SIG,
	ALL_VAOFF_SIG,
	GET_ENERGY_STATE_SIG,

	/*****************sound hint signal********************/
	HINT_CONNECT_SIG,
	HINT_DISCONNECT_SIG,
	HINT_INFO_SIG,
	HINT_SPEAKER_TEST_SIG,
	HINT_FW_VERSION_SIG,
	HINT_SRC_USB_SIG,
	HINT_BT_SEARCH_SIG,
	HINT_DETECT_SEARCH_SIG,
	HINT_EQMOCIE_SIG,
	HINT_EQMUSIC_SIG,
	HINT_EQGAME_SIG,
	HINT_STOP_SIG,
	TOUCH_CALL_SIG,
	TOUCH_TIME_SIG,

	UARTAPP_KEY_SIG,
	UARTAPP_TICK_SIG,

	RESET_SIG,
	RESET_RELEASE_SIG,
	RESET_LONG_PRESS_SIG,
	RESET_LONG_RELEASE_SIG,
	RESET_TICK_SIG,

	PAIR_SIG,
	PAIR_RELEASE_SIG,
	PAIR_LONG_PRESS_SIG,
	PAIR_LONG_RELEASE_SIG,
	PAIR_TICK_SIG,

	DOLBY_SIG,
	DOLBY_RELEASE_SIG,
	DOLBY_LONG_PRESS_SIG,
	DOLBY_LONG_RELEASE_SIG,
	DOLBY_TICK_SIG,
	
	RETURN_SIG,
	RETURN_RELEASE_SIG,
	RETURN_LONG_PRESS_SIG,
	RETURN_LONG_RELEASE_SIG,
	RETURN_TICK_SIG,

	MENU_SIG,
	MENU_RELEASE_SIG,
	MENU_LONG_PRESS_SIG,
	MENU_LONG_RELEASE_SIG,
	MENU_TICK_SIG,

	BT_VOL_SIG,
	VOL_SET_SIG,
	HDMI_VOL_SIG,
	POWER_OFF_RELEASE_SIG,
	BT_UPG_SIG,
	BT_PC_UPG_SIG,
	BT_PLAY_STATUS_SIG,
	BT_PAUSE_STATUS_SIG,
	WIRELESS_TIMER_SIG,
	SETTING_MENU_TIMER_SIG,

	HDMI_INIT_SIG,
	HDMI_HANDLE_SIG,
	HDMI_UPG_SIG,
	HDMI_UPG_SET_SIG,
	SYS_DETECT_TIMER_SIG,
	USER_DELAY_SIG,

ARC_SRC_SIG,
HDMI1_SRC_SIG,
HDMI2_SRC_SIG,

HDMI_D0_MODE_SIG,
HDMI_D4_MODE_SIG,
HDMI_SPDIF_MODE_SIG,

	SCROLL_END_SIG,
	SCROLL_BACK_TIMER_SIG,
	SCROLL_BLINK_ONE_EXIT_SIG,

	BT_UPG_PROCESS_SIG,

	HDMI_HPD_SIG,
	HDMI1_IN_PLUGIN_SIG,
	HDMI2_IN_PLUGIN_SIG,
        BT_CONNECT_CHECK_SIG,
        FACTORY_RESET_HANDLE,

	USB_ENTER_SOURCE_PLA_SIG,
	SWITCH_SRC_DELAY_UNMUTE,
	PASSWORD_TIMEOUT_SIG,

	SYS_CHECK_POWER,
	DISPLAY_ONCE_BACK_SIG,

BASS_SIG,
BASS_RELEASE_SIG,
BASS_LONG_PRESS_SIG,
BASS_LONG_RELEASE_SIG,
BASS_TICK_SIG,

TREBLE_SIG,
TREBLE_RELEASE_SIG,
TREBLE_LONG_PRESS_SIG,
TREBLE_LONG_RELEASE_SIG,
TREBLE_TICK_SIG,

DIM_SIG,
DIM_RELEASE_SIG,
DIM_LONG_PRESS_SIG,
DIM_LONG_RELEASE_SIG,
DIM_TICK_SIG,


UARTAPP_SOURCE_BT_ENTRY_SIG,
UARTAPP_SOURCE_AUX_ENTRY_SIG,
UARTAPP_SOURCE_AUX_EXIT_SIG,
UARTAPP_SOURCE_BT_EXIT_SIG,
	APP_UPG_SIG,
	MCU_UPG_SIG,

	SRC_DELAY_SIG,

	BT_MUTE_ON_SIG,
	BT_MUTE_OFF_SIG,
	OPT_SIG,
	OPT_RELEASE_SIG,
	OPT_LONG_PRESS_SIG,
	OPT_LONG_RELEASE_SIG,
	OPT_TICK_SIG,

	AUX_SIG,
	AUX_RELEASE_SIG,
	AUX_LONG_PRESS_SIG,
	AUX_LONG_RELEASE_SIG,
	AUX_TICK_SIG,

	ARC_SIG,
	ARC_RELEASE_SIG,
	ARC_LONG_PRESS_SIG,
	ARC_LONG_RELEASE_SIG,
	ARC_TICK_SIG,

	HDMI_SIG,
	HDMI_RELEASE_SIG,
	HDMI_LONG_PRESS_SIG,
	HDMI_LONG_RELEASE_SIG,
	HDMI_TICK_SIG,
	
	BASS_UP_SIG,
	BASS_UP_RELEASE_SIG,
	BASS_UP_LONG_PRESS_SIG,
	BASS_UP_LONG_RELEASE_SIG,
	BASS_UP_TICK_SIG,

	BASS_DN_SIG,
	BASS_DN_RELEASE_SIG,
	BASS_DN_LONG_PRESS_SIG,
	BASS_DN_LONG_RELEASE_SIG,
	BASS_DN_TICK_SIG,

	TREBLE_UP_SIG,
	TREBLE_UP_RELEASE_SIG,
	TREBLE_UP_LONG_PRESS_SIG,
	TREBLE_UP_LONG_RELEASE_SIG,
	TREBLE_UP_TICK_SIG,

	TREBLE_DN_SIG,
	TREBLE_DN_RELEASE_SIG,
	TREBLE_DN_LONG_PRESS_SIG,
	TREBLE_DN_LONG_RELEASE_SIG,
	TREBLE_DN_TICK_SIG,

	MUSIC_SIG,
	MUSIC_RELEASE_SIG,
	MUSIC_LONG_PRESS_SIG,
	MUSIC_LONG_RELEASE_SIG,
	MUSIC_TICK_SIG,

	MOVIE_SIG,
	MOVIE_RELEASE_SIG,
	MOVIE_LONG_PRESS_SIG,
	MOVIE_LONG_RELEASE_SIG,
	MOVIE_TICK_SIG,

	NEWS_SIG,
	NEWS_RELEASE_SIG,
	NEWS_LONG_PRESS_SIG,
	NEWS_LONG_RELEASE_SIG,
	NEWS_TICK_SIG,

	NIGHT_SIG,
	NIGHT_RELEASE_SIG,
	NIGHT_LONG_PRESS_SIG,
	NIGHT_LONG_RELEASE_SIG,
	NIGHT_TICK_SIG,

	SPORT_SIG,
	SPORT_RELEASE_SIG,
	SPORT_LONG_PRESS_SIG,
	SPORT_LONG_RELEASE_SIG,
	SPORT_TICK_SIG,

	DIM_UP_SIG,
	DIM_UP_RELEASE_SIG,
	DIM_UP_LONG_PRESS_SIG,
	DIM_UP_LONG_RELEASE_SIG,
	DIM_UP_TICK_SIG,

	DIM_DN_SIG,
	DIM_DN_RELEASE_SIG,
	DIM_DN_LONG_PRESS_SIG,
	DIM_DN_LONG_RELEASE_SIG,
	DIM_DN_TICK_SIG,

	COAXIAL_SIG,
	COAXIAL_RELEASE_SIG,
	COAXIAL_LONG_PRESS_SIG,
	COAXIAL_LONG_RELEASE_SIG,
	COAXIAL_TICK_SIG,

BT_APP_PLAY_STATUS,
BT_APP_PAUSE_STATUS,

	CUSTOMER_PRIVATE_SIG_MAX,
};


#endif // __CUSTOM_SIG_H__

