include $(TOP)/build/scripts/config.mk

DIRS += bt_ao
DIRS += app
DIRS += app/soundhint
DIRS += app/karaoke
DIRS += app/userbt
DIRS += app/user_standby
DIRS += driver/AMP
DIRS += driver/IR
DIRS += usersetting
DIRS += driver/CP
DIRS += display
DIRS += driver/led
DIRS += driver/VFD
DIRS += driver/hdmi_repeater
DIRS += usercmd
DIRS += driver/Wireless
DIRS += voiceAssistant
DIRS += xmldsp
# for dsp tool xml partition
DIRS += dsptool_xml
# for ep firmware update
DIRS += ep_firmware
DIRS += driver/HDMI
DIRS += driver/fifo
DIRS += driver/touch
DIRS += driver/I2C
DIRS += driver/bt
DIRS += driver/uart
DIRS += driver/ite_rep

#excute target build
$(eval $(BUILD_TARGET))
